name: Scott Stamile Front end Web Developer and Designer
description: Personal website and portfolio of Scott Stamile, Front end Web Developer and Designer
url: "https://s8m2s.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: compressed
  sourcemap: never

exclude:
  - config.rb
  - gulpfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - README.md
  - .*
  - CNAME
  - nohup.out
  - vendor